// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
lv_obj_t *ui_scrMain;
lv_obj_t *ui_background;
lv_obj_t *ui_links;
lv_obj_t *ui_bsky;
lv_obj_t *ui_masto;
lv_obj_t *ui_twitter;
lv_obj_t *ui_github;
lv_obj_t *ui_youtube;
lv_obj_t *ui_twitch;
lv_obj_t *ui_telegram;
lv_obj_t *ui_discord;
lv_obj_t *ui_fa;
lv_obj_t *ui_avatar;
lv_obj_t *ui_name;
lv_obj_t *ui_username;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_protolulu_[2] = {&ui_img_protolulu_128_png, &ui_img_protolulu_192_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_scrMain_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_scrMain);
}
