// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
extern lv_obj_t *ui_scrMain;
extern lv_obj_t *ui_background;
extern lv_obj_t *ui_links;
extern lv_obj_t *ui_bsky;
extern lv_obj_t *ui_masto;
extern lv_obj_t *ui_twitter;
extern lv_obj_t *ui_github;
extern lv_obj_t *ui_youtube;
extern lv_obj_t *ui_twitch;
extern lv_obj_t *ui_telegram;
extern lv_obj_t *ui_discord;
extern lv_obj_t *ui_fa;
extern lv_obj_t *ui_avatar;
extern lv_obj_t *ui_name;
extern lv_obj_t *ui_username;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ps1_background_png);   // assets/ps1_background.png
LV_IMG_DECLARE( ui_img_bsky_png);   // assets/bsky.png
LV_IMG_DECLARE( ui_img_masto_png);   // assets/masto.png
LV_IMG_DECLARE( ui_img_twitter_png);   // assets/twitter.png
LV_IMG_DECLARE( ui_img_github_png);   // assets/github.png
LV_IMG_DECLARE( ui_img_youtube_png);   // assets/youtube.png
LV_IMG_DECLARE( ui_img_twitch_png);   // assets/twitch.png
LV_IMG_DECLARE( ui_img_telegram_png);   // assets/telegram.png
LV_IMG_DECLARE( ui_img_discord_png);   // assets/discord.png
LV_IMG_DECLARE( ui_img_fa_png);   // assets/fa.png
LV_IMG_DECLARE( ui_img_protolulu_192_png);   // assets/protolulu_192.png
LV_IMG_DECLARE( ui_img_username_png);   // assets/username.png
LV_IMG_DECLARE( ui_img_protolulu_128_png);   // assets/protolulu_128.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
