// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrSocial7_screen_init(void)
{
ui_scrSocial7 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrSocial7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_socialPanel7 = lv_obj_create(ui_scrSocial7);
lv_obj_set_width( ui_socialPanel7, 320);
lv_obj_set_height( ui_socialPanel7, 240);
lv_obj_set_align( ui_socialPanel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_socialPanel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_qr7 = lv_img_create(ui_socialPanel7);
lv_img_set_src(ui_qr7, &ui_img_social7_qr_png);
lv_obj_set_width( ui_qr7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_qr7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_qr7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_qr7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qr7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back7 = lv_btn_create(ui_socialPanel7);
lv_obj_set_width( ui_back7, 50);
lv_obj_set_height( ui_back7, 32);
lv_obj_set_x( ui_back7, -5 );
lv_obj_set_y( ui_back7, -5 );
lv_obj_add_flag( ui_back7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backLabel7 = lv_label_create(ui_back7);
lv_obj_set_width( ui_backLabel7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backLabel7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backLabel7, LV_ALIGN_CENTER );
lv_label_set_text(ui_backLabel7,"Back");

lv_obj_add_event_cb(ui_back7, ui_event_back7, LV_EVENT_ALL, NULL);

}
