// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrSocial8_screen_init(void)
{
ui_scrSocial8 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrSocial8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_socialPanel8 = lv_obj_create(ui_scrSocial8);
lv_obj_set_width( ui_socialPanel8, 320);
lv_obj_set_height( ui_socialPanel8, 240);
lv_obj_set_align( ui_socialPanel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_socialPanel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_qr8 = lv_img_create(ui_socialPanel8);
lv_img_set_src(ui_qr8, &ui_img_social8_qr_png);
lv_obj_set_width( ui_qr8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_qr8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_qr8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_qr8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qr8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back8 = lv_btn_create(ui_socialPanel8);
lv_obj_set_width( ui_back8, 50);
lv_obj_set_height( ui_back8, 32);
lv_obj_set_x( ui_back8, -5 );
lv_obj_set_y( ui_back8, -5 );
lv_obj_add_flag( ui_back8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backLabel8 = lv_label_create(ui_back8);
lv_obj_set_width( ui_backLabel8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backLabel8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backLabel8, LV_ALIGN_CENTER );
lv_label_set_text(ui_backLabel8,"Back");

lv_obj_add_event_cb(ui_back8, ui_event_back8, LV_EVENT_ALL, NULL);

}
