// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrSocial6_screen_init(void)
{
ui_scrSocial6 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrSocial6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_socialPanel6 = lv_obj_create(ui_scrSocial6);
lv_obj_set_width( ui_socialPanel6, 320);
lv_obj_set_height( ui_socialPanel6, 240);
lv_obj_set_align( ui_socialPanel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_socialPanel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_qr6 = lv_img_create(ui_socialPanel6);
lv_img_set_src(ui_qr6, &ui_img_social6_qr_png);
lv_obj_set_width( ui_qr6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_qr6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_qr6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_qr6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qr6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back6 = lv_btn_create(ui_socialPanel6);
lv_obj_set_width( ui_back6, 50);
lv_obj_set_height( ui_back6, 32);
lv_obj_set_x( ui_back6, -5 );
lv_obj_set_y( ui_back6, -5 );
lv_obj_add_flag( ui_back6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backLabel6 = lv_label_create(ui_back6);
lv_obj_set_width( ui_backLabel6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backLabel6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backLabel6, LV_ALIGN_CENTER );
lv_label_set_text(ui_backLabel6,"Back");

lv_obj_add_event_cb(ui_back6, ui_event_back6, LV_EVENT_ALL, NULL);

}
