// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrSocial2_screen_init(void)
{
ui_scrSocial2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrSocial2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_socialPanel2 = lv_obj_create(ui_scrSocial2);
lv_obj_set_width( ui_socialPanel2, 320);
lv_obj_set_height( ui_socialPanel2, 240);
lv_obj_set_align( ui_socialPanel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_socialPanel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_qr2 = lv_img_create(ui_socialPanel2);
lv_img_set_src(ui_qr2, &ui_img_social2_qr_png);
lv_obj_set_width( ui_qr2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_qr2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_qr2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_qr2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qr2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back2 = lv_btn_create(ui_socialPanel2);
lv_obj_set_width( ui_back2, 50);
lv_obj_set_height( ui_back2, 32);
lv_obj_set_x( ui_back2, -5 );
lv_obj_set_y( ui_back2, -5 );
lv_obj_add_flag( ui_back2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backLabel2 = lv_label_create(ui_back2);
lv_obj_set_width( ui_backLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_backLabel2,"Back");

lv_obj_add_event_cb(ui_back2, ui_event_back2, LV_EVENT_ALL, NULL);

}
