// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrSocial3_screen_init(void)
{
ui_scrSocial3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrSocial3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_socialPanel3 = lv_obj_create(ui_scrSocial3);
lv_obj_set_width( ui_socialPanel3, 320);
lv_obj_set_height( ui_socialPanel3, 240);
lv_obj_set_align( ui_socialPanel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_socialPanel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_qr3 = lv_img_create(ui_socialPanel3);
lv_img_set_src(ui_qr3, &ui_img_social3_qr_png);
lv_obj_set_width( ui_qr3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_qr3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_qr3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_qr3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qr3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back3 = lv_btn_create(ui_socialPanel3);
lv_obj_set_width( ui_back3, 50);
lv_obj_set_height( ui_back3, 32);
lv_obj_set_x( ui_back3, -5 );
lv_obj_set_y( ui_back3, -5 );
lv_obj_add_flag( ui_back3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backLabel3 = lv_label_create(ui_back3);
lv_obj_set_width( ui_backLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_backLabel3,"Back");

lv_obj_add_event_cb(ui_back3, ui_event_back3, LV_EVENT_ALL, NULL);

}
