// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrSocial4_screen_init(void)
{
ui_scrSocial4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrSocial4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_socialPanel4 = lv_obj_create(ui_scrSocial4);
lv_obj_set_width( ui_socialPanel4, 320);
lv_obj_set_height( ui_socialPanel4, 240);
lv_obj_set_align( ui_socialPanel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_socialPanel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_qr4 = lv_img_create(ui_socialPanel4);
lv_img_set_src(ui_qr4, &ui_img_social4_qr_png);
lv_obj_set_width( ui_qr4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_qr4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_qr4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_qr4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qr4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back4 = lv_btn_create(ui_socialPanel4);
lv_obj_set_width( ui_back4, 50);
lv_obj_set_height( ui_back4, 32);
lv_obj_set_x( ui_back4, -5 );
lv_obj_set_y( ui_back4, -5 );
lv_obj_add_flag( ui_back4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backLabel4 = lv_label_create(ui_back4);
lv_obj_set_width( ui_backLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_backLabel4,"Back");

lv_obj_add_event_cb(ui_back4, ui_event_back4, LV_EVENT_ALL, NULL);

}
