// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrSocial5_screen_init(void)
{
ui_scrSocial5 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_scrSocial5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_socialPanel5 = lv_obj_create(ui_scrSocial5);
lv_obj_set_width( ui_socialPanel5, 320);
lv_obj_set_height( ui_socialPanel5, 240);
lv_obj_set_align( ui_socialPanel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_socialPanel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_qr5 = lv_img_create(ui_socialPanel5);
lv_img_set_src(ui_qr5, &ui_img_social5_qr_png);
lv_obj_set_width( ui_qr5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_qr5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_qr5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_qr5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qr5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_back5 = lv_btn_create(ui_socialPanel5);
lv_obj_set_width( ui_back5, 50);
lv_obj_set_height( ui_back5, 32);
lv_obj_set_x( ui_back5, -5 );
lv_obj_set_y( ui_back5, -5 );
lv_obj_add_flag( ui_back5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backLabel5 = lv_label_create(ui_back5);
lv_obj_set_width( ui_backLabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_backLabel5,"Back");

lv_obj_add_event_cb(ui_back5, ui_event_back5, LV_EVENT_ALL, NULL);

}
